### ISSUE TITLE
Error: RPC_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by Xart3mis** [devsnek/discord-rich-presence#26]
### everytime i start the app i get this error 

Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (D:\Documents\Nodejs\Electron\4anime-app\node_modules\discord-rpc\src\client.js:107:47)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: RPC_CONNECTION_TIMEOUT
      at Timeout._onTimeout (D:\Documents\Nodejs\Electron\4anime-app\node_modules\discord-rpc\src\client.js:107:47)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}

here's the code 

```
function updateDiscordRPC() {
	const client = require("discord-rich-presence")("removed for privacy");

	client.on("connected", () => {
		console.log("connected!");
	});

	client.updatePresence({
		state: "Watchin Anime",
		details: `watching ${getCurrentUrl}`,
		largeImageKey: "logo",
		instance: false,
		elapsedTime: new Date(),
	});
}
```
full project is [here](https://www.github.com/Xart3mis/4anime-app)

**Comment by DylanD16** [comment]
Why are you running updatePresence

**Comment by Sv443** [comment]
`elapsedTime` has to be an epoch number, not a Date object. Try to replace `new Date()` with `Date.now()` or `new Date().getTime()`

**Comment by GiovanH** [comment]
https://github.com/devsnek/discord-rich-presence/blob/e7c9d0b76e463d3f92e70ba58aad4a2bb1726608/test.js#L27 uses `new Date()`.
