### ISSUE TITLE
Errors when reuire and use

### ISSUE THREAD

**Issue by gorlik1337** [devsnek/discord-rich-presence#5]
on require
```
(node:2498) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/home/pi/discordbot/node_modules/discord-rpc/src/transports/IPC.js:135:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:2498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

when using updatePresence
```
(node:2476) UnhandledPromiseRejectionWarning: Error [RPC_CONNECTION_TIMEOUT]
    at Timeout.setTimeout (/home/pi/discordbot/node_modules/discord-rpc/src/Client.js:110:47)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
(node:2476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by devsnek** [comment]
you have to run in on the same computer your discord client is installed on

**Comment by Charsy89** [comment]
Does it affect anything when using Linux? I am running this on the same computer discord is installed (and running) on
