### ISSUE TITLE
Unhandled error.

### ISSUE THREAD

**Issue by ledlamp** [devsnek/discord-rich-presence#7]
```
$ node -e "require('discord-rich-presence')('417686773074886666')"
```
```
(node:25513) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at RP.emit (events.js:171:17)
    at rpc.login.then.catch (/Users/me/discord-chrome-presence-master/node_modules/discord-rich-presence/index.js:54:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have also tried ID `484805938608603140` and `180984871685062656`.

**Comment by ledlamp** [comment]
Found issue. Package was referring to older version 0.0.6.
