### ISSUE TITLE
Error 4000

### ISSUE THREAD

**Issue by Feuerhamster** [devsnek/discord-rich-presence#9]
Hello everyone.

I would like to use this module but it doesn't work.

When the program starts, i get this error:
`{ code: 4000, message: 'No Client ID Specified' }`

I've already installed discord-rpc to my project.

The full code is the same as the example in Readme.md

best greetings,
Feuerhamster

**Comment by AngryKiller** [comment]
Well, as the error said, you didn't specify a Client ID like in the example.

**Comment by AngryKiller** [comment]
You probably have to put your own client id, and not use the one in the example

**Comment by Feuerhamster** [comment]
With my own Client id, i get this:
```
(node:4864) UnhandledPromiseRejectionWarning: RangeError: timestamps.start must fit into a unix timestamp
    at RPCClient.setActivity (D:\Projekte\DiscordRPC\node_modules\discord-rich-presence\node_modules\discord-rpc\src\Client.js:484:15)
    at rpc.login.then (D:\Projekte\DiscordRPC\node_modules\discord-rich-presence\index.js:59:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by devsnek** [comment]
There are no bugs here. come to the discord support server for random help questions. https://discord.gg/bRCvFy9
